server:
  port: 8080


spring:
  datasource:
    username: root
    password: qinyuqin
    url: jdbc:mysql://localhost:3306/employee?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver




